### ISSUE TITLE
Crashing on TParty

### ISSUE THREAD

**Issue by simonkeenlyside** [z16/Lua#51]
I can log in, and play on 3 of my 4 characters, but every time I log in my main character, the game crashes within 10 seconds of an image displaying. The error message says that the fault is TParty. I keep looking in the windower crash log, but nothing shows up in there. Help please!!!

**Comment by z16** [comment]
Can you post the precise error message? A screenshot would be best, but the exact text would also do.

**Comment by simonkeenlyside** [comment]
I've attached a sc of my character booting up. And the failure message says
![ffxi_2017 05 22_22 46 05](https://cloud.githubusercontent.com/assets/28171134/26337757/c6b382f4-3f40-11e7-8a8a-75ffa260b901.png)
:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pol.exe
  Application Version:	1.18.13.0
  Application Timestamp:	4e3bcddc
  Fault Module Name:	tparty.DLL
  Fault Module Version:	1.2.2.9
  Fault Module Timestamp:	5460b5ae
  Exception Code:	c0000005
  Exception Offset:	00004ed7
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
![ffxi_2017 05 22_22 46 05](https://cloud.githubusercontent.com/assets/28171134/26337741/aadb8ec8-3f40-11e7-90db-99fbf4daf779.png)

  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by z16** [comment]
It looks like you're still using *TParty* as a plugin, which has been discontinued several years ago. You can't even load it with our launcher, which means you're manually loading it somehow, probably through your `Windower/scripts/init.txt` file. In there you'll probably find lines like "load tparty" and similar lines. Remove all of them, you should not load any plugins in there.

Now open Windower, and you'll see three tabs at the top, *Profiles*, *Addons* and *Plugins*. You can browse the *Addons* and *Plugins* tabs and enable what you want. You'll find that the *Plugins* section is much reduced from years ago, and several plugins have since been recreated as addons, *TParty* being one of them.

Here's a [full list](https://gist.github.com/z16/f73d0912e5c5ed02c58b).

**Comment by simonkeenlyside** [comment]
Awesome! That fixed it, thank you!!! in the Windower/plugins folder should I keep the TParty.dll? Or should I just ignore this now?

**Comment by z16** [comment]
You can safely delete it, nothing uses it anymore (and it doesn't work, as you could see 😄)
